services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      ONLINE_MODE: "FALSE"
      MODE: "creative"
      SEED: "4730575252807339304"
      DIFFICULTY: "peaceful"
    volumes:
      - ./data:/data
    restart: unless-stopped
